DROP TABLE IF EXISTS `venta_shadow`;
CREATE TABLE `venta_shadow` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `venta_id` bigint(20) NOT NULL,
  `local_id` bigint(20) DEFAULT NULL,
  `id_documento` char(2) NOT NULL,
  `id_cliente` bigint(20) NOT NULL,
  `id_vendedor` bigint(20) DEFAULT NULL,
  `condicion_pago` bigint(20) DEFAULT NULL,
  `id_moneda` int(11) DEFAULT NULL,
  `venta_status` varchar(45) DEFAULT NULL,
  `fecha` datetime DEFAULT NULL,
  `fecha_facturacion` datetime DEFAULT NULL,
  `serie` varchar(45) DEFAULT NULL,
  `numero` varchar(45) DEFAULT NULL,
  `factura_impresa` tinyint(2) DEFAULT 0,
  `subtotal` decimal(18,2) DEFAULT NULL,
  `total_impuesto` decimal(18,2) DEFAULT NULL,
  `total` decimal(18,2) DEFAULT NULL,
  `pagado` decimal(18,2) DEFAULT 0.00,
  `vuelto` decimal(18,2) DEFAULT 0.00,
  `tasa_cambio` decimal(4,2) DEFAULT NULL,
  `dni_garante` varchar(20) DEFAULT NULL,
  `tipo_impuesto` tinyint(1) DEFAULT NULL,
  `comprobante_id` int(11) DEFAULT 0,
  `nota` longtext DEFAULT NULL,
  `nro_guia` int(11) DEFAULT NULL COMMENT 'Correlativo de la guia de remision',
  `inicial` decimal(6,2) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `nota_facturada` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `venta_id` (`venta_id`),
  KEY `local_id` (`local_id`),
  KEY `id_documento` (`id_documento`),
  KEY `id_cliente` (`id_cliente`),
  KEY `id_vendedor` (`id_vendedor`),
  KEY `condicion_pago` (`condicion_pago`),
  KEY `id_moneda` (`id_moneda`),
  CONSTRAINT `venta_shadow_ibfk_1` FOREIGN KEY (`venta_id`) REFERENCES `venta` (`venta_id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `venta_shadow_ibfk_2` FOREIGN KEY (`local_id`) REFERENCES `local` (`int_local_id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `venta_shadow_ibfk_4` FOREIGN KEY (`id_cliente`) REFERENCES `cliente` (`id_cliente`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `venta_shadow_ibfk_5` FOREIGN KEY (`id_vendedor`) REFERENCES `usuario` (`nUsuCodigo`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `venta_shadow_ibfk_6` FOREIGN KEY (`condicion_pago`) REFERENCES `condiciones_pago` (`id_condiciones`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `venta_shadow_ibfk_7` FOREIGN KEY (`id_moneda`) REFERENCES `moneda` (`id_moneda`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `venta_shadow_detalle`;
CREATE TABLE `venta_shadow_detalle` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `id_venta_shadow` bigint(20) DEFAULT NULL,
  `id_producto` bigint(20) DEFAULT NULL,
  `precio` decimal(18,2) DEFAULT NULL,
  `cantidad` decimal(18,3) NOT NULL DEFAULT 0.000,
  `unidad_medida` bigint(20) DEFAULT NULL,
  `detalle_importe` decimal(18,2) DEFAULT NULL,
  `detalle_costo_promedio` decimal(18,2) DEFAULT 0.00,
  `detalle_costo_ultimo` decimal(18,2) DEFAULT 0.00,
  `detalle_utilidad` decimal(18,2) DEFAULT 0.00,
  `impuesto_id` int(11) DEFAULT NULL,
  `afectacion_impuesto` varchar(2) NOT NULL,
  `impuesto_porciento` decimal(18,2) DEFAULT NULL,
  `precio_venta` decimal(18,2) DEFAULT 0.00,
  `tipo_impuesto_compra` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id_producto` (`id_producto`),
  KEY `id_venta_shadow` (`id_venta_shadow`),
  KEY `unidad_medida` (`unidad_medida`),
  CONSTRAINT `venta_shadow_detalle_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `producto` (`producto_id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `venta_shadow_detalle_ibfk_2` FOREIGN KEY (`id_venta_shadow`) REFERENCES `venta_shadow` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `venta_shadow_detalle_ibfk_3` FOREIGN KEY (`unidad_medida`) REFERENCES `unidades` (`id_unidad`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;